#### **IMPORTANDO LIBRERÍA NUMPY**


In [1]:
import numpy as np

##### Creando una lista de 10 Elementos


In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Arreglo de 2 en 2 utilizando arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>

In [11]:
promedio = np.mean(arreglo)
promedio
np.float64(5.5)
#mediana no es lo mismo que promedio

np.float64(5.5)

#### Obteniendo la mediana de array

In [12]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

#### Desviación estandar del arreglo

In [13]:
desviacion_std = np.ones(10)
desviacion_std

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Generación de un arreglo de 10 elementos de solos unos

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Generación de un arreglo de 10 elementos de solo ceros

In [15]:
arreglo_de_ceros = np.zeros(10)
arreglo_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Transformando el arreglo de unos de punto flotante a enteros

In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>

In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.46833639, 0.75492407, 0.5310016 , 0.90973087, 0.15694328,
       0.66555305, 0.24650516, 0.09654421, 0.53553117, 0.14675294])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [ ]:
matriz = np.random.rand(3,3)
matriz
#Primer parametro son las filas y el segundo las columnas

array([[0.61578934, 0.45273808, 0.23570378],
       [0.77002738, 0.25153585, 0.39698026],
       [0.81276502, 0.1119966 , 0.08009381]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>

In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([753, 412, 133, 130, 340,  65, 599, 984, 545, 165], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [ ]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2
#el tercer parametro es la cantidad de elementos que quiero que se genere

array([[84, 72, 75, 10, 26,  2, 10,  6, 81, 40],
       [81, 81, 46,  9, 84, 97, 96, 26, 75, 54],
       [20, 23, 44, 32, 85, 18, 92, 42, 98, 71],
       [39, 31, 80, 28, 17, 40, 87, 38, 25, 14],
       [28, 85, 66, 24, 40, 81, 19, 45, 43, 90],
       [19, 95, 71, 49, 88, 99, 20, 60, 47, 33],
       [78, 42, 51, 99, 17, 37, 84,  8,  4,  1],
       [94, 25, 32, 38, 93, 73,  5, 14, 87, 46],
       [91, 17, 55, 18, 21, 97, 96, 88, 86,  2],
       [82, 43, 48, 36,  7, 53, 77, 51, 82, 32]], dtype=int32)